/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e7e8e9",
        "primary-fixed-dim": "#b2c5ff",
        "outline-variant": "#c3c6d6",
        "primary-fixed": "#dae2ff",
        "on-surface-variant": "#434654",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb59b",
        "primary-container": "#0052cc",
        "on-error": "#ffffff",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed": "#380d00",
        "secondary-fixed-dim": "#b4c5fb",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#021945",
        "error": "#ba1a1a",
        "surface-bright": "#f8f9fa",
        "on-tertiary-fixed-variant": "#812800",
        "inverse-surface": "#2e3132",
        "secondary-container": "#b6c8fe",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#edeeef",
        "on-surface": "#191c1d",
        "primary": "#003d9b",
        "on-primary-container": "#c4d2ff",
        "tertiary": "#7b2600",
        "on-tertiary-container": "#ffc6b2",
        "on-secondary-fixed-variant": "#344573",
        "secondary-fixed": "#dae2ff",
        "inverse-primary": "#b2c5ff",
        "tertiary-container": "#a33500",
        "surface-container-highest": "#e1e3e4",
        "inverse-on-surface": "#f0f1f2",
        "surface-tint": "#0c56d0",
        "outline": "#737685",
        "on-primary-fixed-variant": "#0040a2",
        "on-primary-fixed": "#001848",
        "on-primary": "#ffffff",
        "secondary": "#4c5d8d",
        "on-background": "#191c1d",
        "surface-dim": "#d9dadb",
        "on-secondary-container": "#415382",
        "error-container": "#ffdad6",
        "surface": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "background": "#f8f9fa",
        "tertiary-fixed": "#ffdbcf",
        "on-secondary": "#ffffff"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        display: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}